### ISSUE TITLE
MEMORY LEAK

### ISSUE THREAD

**Issue by Septembers** [Sples1/ENT_Classes-and-roles#2]
L 10/29/2020 - 13:09:26: [SM] MEMORY LEAK DETECTED IN PLUGIN (file "jail/ent_cnr.smx")
L 10/29/2020 - 13:09:26: [SM] Unloading plugin to free 27450 handles.
L 10/29/2020 - 13:09:26: [SM] Contact the author(s) of this plugin to correct this error.
L 10/29/2020 - 13:09:26: --------------------------------------------------------------------------
L 10/29/2020 - 13:09:26: Type	IBaseMenu           |	Count	27413
L 10/29/2020 - 13:09:26: Type	Timer               |	Count	33
L 10/29/2020 - 13:09:26: Type	Cookie              |	Count	4
L 10/29/2020 - 13:09:26: -- Approximately 3158528 bytes of memory are in use by (27450) Handles.

**Comment by Sples1** [comment]
Probably fixed in the 0.3 version. Please give me a feedback about it. <3

**Comment by Sples1** [comment]
**Ticket closed, because the problem seems to be fixed.**
